### ISSUE TITLE
作者，上传图片失败是怎么回事呀？

### ISSUE THREAD

**Issue by ice-orange-xi** [yrucrew/ssm-demo#2]
四月 06, 2019 9:21:05 下午 org.apache.catalina.core.StandardWrapperValve invoke
严重: Servlet.service() for servlet [springmvc] in context with path [/weibo] threw exception
java.io.FileNotFoundException: E:\upload\userface\735f5da8-3596-40c2-868c-713a2a9418ab.jpeg (系统找不到指定的路径。)

**Comment by quan7u** [comment]
你可能没有创建这个目录'E:\upload\userface\'吧？

**Comment by TenXLiar** [comment]
作者你好，如果实现上传图片的话，需要做哪些操作啊。(刚开始学，有很多不太懂。目录我也创建了，上传还是失败，跳转到500.jsp

**Comment by quan7u** [comment]
@ice-orange-xi @TenXLiar 我修改了README文件 第四点 不好意思 是我的疏忽
