### ISSUE TITLE
作者你好，我想问一下，头像的上传和微博图片的上传保存路径是否是相同的啊。

### ISSUE THREAD

**Issue by TenXLiar** [yrucrew/ssm-demo#3]
作者你好，我想问一下，头像的上传和微博图片的上传保存路径是否是相同的啊。我看代码好像设置的都是upload/userface,我修改了头像路径为impUpload，可是在该文件夹里看不到相关的上传图片，比较疑惑。是不是docbase和path设置的有问题？求解答

**Comment by quan7u** [comment]
可以自己定义不同的上传目录
