### ISSUE TITLE
显示服务器错误

### ISSUE THREAD

**Issue by xianglli** [yrucrew/ssm-demo#6]
环境是 ubuntu 16.04 + tomcat8 + mysql 。数据库确定权限没有问题， 使用 mavenn命令 mvn clean package -DskipTests 后 生成.war文件成功。网站在登录时无法正常登录，显示服务器错误

**Comment by xianglli** [comment]
在注册的时候也会提示服务器错误

**Comment by quan7u** [comment]
请给出完整的报错日志
